"""This module contains a collection of labels for KITTI."""
kitti_global_id_to_labels = {
    0: 'unlabeled', 1: 'ego vehicle', 2: 'rectification border', 3: 'out of roi', 4: 'static',
    5: 'dynamic', 6: 'ground', 7: 'road', 8: 'sidewalk', 9: 'parking', 10: 'rail track',
    11: 'building', 12: 'wall', 13: 'fence', 14: 'guard rail', 15: 'bridge', 16: 'tunnel',
    17: 'pole', 18: 'polegroup', 19: 'traffic light', 20: 'traffic sign', 21: 'vegetation',
    22: 'terrain', 23: 'sky', 24: 'person', 25: 'rider', 26: 'car', 27: 'truck', 28: 'bus',
    29: 'caravan', 30: 'trailer', 31: 'train', 32: 'motorcycle', 33: 'bicycle', 34: 'garage',
    35: 'gate', 36: 'stop', 37: 'smallpole', 38: 'lamp', 39: 'trash bin', 40: 'vending machine',
    41: 'box', 42: 'unknown construction', 43: 'unknown vehicle', 44: 'unknown object',
    -1: 'license plate'}

IGNORE_CLASS = 0

kitti_global_id_to_spt_train_id = {
    0: IGNORE_CLASS,
    1: IGNORE_CLASS,
    2: IGNORE_CLASS,
    3: IGNORE_CLASS,
    4: IGNORE_CLASS,
    5: IGNORE_CLASS,
    6: IGNORE_CLASS,
    7: 1,
    8: 2,
    9: IGNORE_CLASS,
    10: IGNORE_CLASS,
    11: 3,
    12: 4,
    13: 5,
    14: IGNORE_CLASS,
    15: IGNORE_CLASS,
    16: IGNORE_CLASS,
    17: 6,
    18: IGNORE_CLASS,
    19: 7,
    20: 8,
    21: 9,
    22: 10,
    23: IGNORE_CLASS,
    24: 11,
    25: IGNORE_CLASS,
    26: 12,
    27: 13,
    28: IGNORE_CLASS,
    29: IGNORE_CLASS,
    30: IGNORE_CLASS,
    31: IGNORE_CLASS,
    32: 14,
    33: 15,
    34: 3,
    35: 5,
    36: IGNORE_CLASS,
    37: 6,
    38: IGNORE_CLASS,
    39: IGNORE_CLASS,
    40: IGNORE_CLASS,
    41: IGNORE_CLASS,
    42: IGNORE_CLASS,
    43: IGNORE_CLASS,
    44: IGNORE_CLASS,
    -1: IGNORE_CLASS
}

kitti_spt_train_id_to_labels = {
    IGNORE_CLASS: 'unlabeled',
    1: 'road',
    2: 'sidewalk',
    3: 'building',
    4: 'wall',
    5: 'fence',
    6: 'pole',
    7: 'traffic light',
    8: 'traffic sign',
    9: 'vegetation',
    10: 'terrain',
    11: 'person',
    12: 'car',
    13: 'truck',
    14: 'motorcycle',
    15: 'bicycle',
}

kitti_spt_train_id_to_ru_labels = {
    IGNORE_CLASS: 'Без разметки',
    1: 'Дорога',
    2: 'Тротуар',
    3: 'Здание',
    4: 'Стена',
    5: 'Забор',
    6: 'Столб',
    7: 'Светофор',
    8: 'Дорожный знак',
    9: 'Крупная растительность',
    10: 'Трава',
    11: 'Человек',
    12: 'Легковой автомобиль',
    13: 'Грузовик',
    14: 'Мотоцикл',
    15: 'Велосипед',
}

kitti_spt_labels_to_ru_labels = {
    'unlabeled': 'Без разметки',
    'road': 'Дорога',
    'sidewalk': 'Тротуар',
    'building': 'Здание',
    'wall': 'Стена',
    'fence': 'Забор',
    'pole': 'Столб',
    'traffic light': 'Светофор',
    'traffic sign': 'Дорожный знак',
    'vegetation': 'Крупная растительность',
    'terrain': 'Трава',
    'person': 'Человек',
    'car': 'Легковой автомобиль',
    'truck': 'Грузовик',
    'motorcycle': 'Мотоцикл',
    'bicycle': 'Велосипед',
}

SPT_KITTI_NUM_CLASSES = len(kitti_spt_train_id_to_labels)
